/*=========S03F-SALESORDER-FFO (Z4KE/Z4KR) - COMPANY STORE===============*/
/* COMPANY STORE VERSION:
 - SHIP_TO: Dynamic from ETA User Fields based on GA_DOMAINE
 - GFM_TYPETARIF: 'CSRSP' instead of 'KRRSP'
 - CONTRACTTYPE: Hardcoded K2
 - Company Store Filter: ET_LIBREET1 = '006'
*/
SELECT A.GP_NATUREPIECEG AS CEGID_DOCS_TYPE
	,'KR' AS SAP_COUNTRY_CODE
	,'8591' AS SALES_ORG
	,CASE
		WHEN GP_NATUREPIECEG = 'FFO' AND GP_LIBREPIECE1 = 'Z09001'
			THEN '14'
		ELSE '11'
	END AS DIST_CHANNEL
	,ET_CHARLIBRE1 AS SOLD_TO
	/* =============================================
	   COMPANY STORE: SHIP_TO mapped by GA_domaine -> BP codes in User Fields 1-6
	   ============================================= */
	,CASE
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'SHI' THEN SHIBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'CPB' THEN CPBBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'NAR' THEN NARBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'DRE' THEN DREBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'FRA' THEN FRABP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'CPC' THEN CPCBP.MUD_VALCHAMP
		ELSE ET_CHARLIBRE2
	END AS SHIP_TO
	,A.GP_REPRESENTANT + ' ' + GCL_LIBELLE AS SENDER_BC
	,'' AS RECEIPIENT_BC
	,CASE
		/* FFO: BASED ON GL_QTEFACT */
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT < 0
			THEN 'Z4KR'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT >= 0 AND A.GP_ETATCOMPTA = 'AT2'
			AND GL_PUTTCBASE <> 0
			AND GL_QTEFACT > 0
			AND GL_PUTTCBASE * GL_QTEFACT <> GL_TOTALTTC
			THEN 'Z4KE'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT >= 0
			AND GL_QTEFACT > 0
			AND GL_PUTTCBASE * GL_QTEFACT = GL_TOTALTTC
			THEN 'Z4KE'
		ELSE ''
	END AS SALES_ORDER_TYPE
	,'Z517' AS PO_TYPE
	,CASE
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT < 0
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4KR'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT >= 0
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4KE'
		WHEN A.GP_NATUREPIECEG = 'FFO'
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4IO'
		ELSE ''
	END AS CUSTREF
	,CONVERT(NVARCHAR(8), A.GP_DATEPIECE, 112) AS PO_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATEPIECE, 112) AS REQUEST_DELIVERY_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATEPIECE, 112) AS CONTRACT_START_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATEPIECE+1, 112) AS CONTRACT_END_DATE
	,(
		SELECT YX_LIBELLE
		FROM CHOIXEXT
		WHERE YX_TYPE = 'GTL'
			AND YX_CODE LIKE 'Z01%'
			AND YX_ABREGE = ET_LIBREET9 + '-' + GL_MOTIFMVT
		) AS COST_CENTER
	,RIGHT('000000' + STR(GL_NUMORDRE), 6) AS ITEM_LINE_NUMBER
	,CASE
		WHEN GL_QTEFACT > 0
			THEN GL_QTEFACT
		ELSE ABS(GL_QTEFACT)
	END AS ORDER_QUANTITY
	,ARTICLEDIM_MODE.GDI_LIBELLE_1 AS MATERIAL_NUMBER
	,'ZMP2' AS CONDITION_TYPE
	,IIF(GL_LIBREART6 = 'Z002' OR GL_QTEFACT = 0, '0', (
		CASE
			WHEN ISNULL(GL_TOTALTTC, 0) > 0
				THEN GL_TOTALTTC / GL_QTEFACT
			ELSE CASE
					WHEN (GL_TOTALTTC = 0) THEN 0
					ELSE CASE
							WHEN ISNULL(GL_PUTTCBASE, 0) = 0 AND ISNULL(GF_PRIXUNITAIRE, 0) <> 0
								THEN ABS(ROUND(ISNULL(GF_PRIXUNITAIRE, 0), 2))
							ELSE ABS(ROUND(ISNULL(GL_PUTTC, 0), 2))
							END
					END
			END
		)) AS RETAIL_PRICE
	,'' AS DISC_CONDITION_TYPE
	,'' AS DISCOUNT_AMT
	,CASE
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT >= 0 AND GL_LIBREART6 = 'Z002' THEN 'Z4K1'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT < 0 AND GL_LIBREART6 = 'Z002' THEN 'Z4K2'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT < 0 AND GL_LIBREART6 = 'Z001' THEN 'KRN'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT >= 0 AND GL_LIBREART6 <> 'Z002' AND GL_TOTALTTC = 0 THEN 'Z4K1'
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT >= 0 AND GL_LIBREART6 <> 'Z002' AND GL_TOTALTTC <> 0 THEN 'KEN'
		WHEN A.GP_NATUREPIECEG = 'FFO' THEN 'TANN'
		ELSE ''
	END AS ITEM_CAT
	,'' AS SURCHARGE
	,CASE
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT > 0 THEN ''
		WHEN A.GP_NATUREPIECEG = 'FFO' AND GL_QTEFACT < 0
			THEN CASE WHEN GL_MOTIFMVT = 'S04' THEN '519' ELSE '421' END
		ELSE '400'
	END AS ORDER_REASON
	,'8591' AS PLANT
	,'' AS SLOC
	,ARTICLEDIM_MODE.GDI_LIBELLE AS BATCH
	,CAST(ET_CHARLIBRE3 AS VARCHAR) + CONVERT(VARCHAR(8), NOW(), 112) + REPLACE(CONVERT(VARCHAR(5), ADDHOURS(NOW(), -7), 108), ':', '') AS MESSAGE_ID
	,CONVERT(VARCHAR(8), A.GP_DATEPIECE, 112) AS DATE
	,REPLACE(CONVERT(VARCHAR(5), ADDHOURS(NOW(), -7), 108), ':', '') AS TIME
	,CASE
		WHEN GL_QTEFACT < 0 THEN 'Z4KR'
		WHEN GL_LIBREART6 = 'Z002' THEN 'Z4FC'
		ELSE 'Z4KE'
	END AS ORDER_TYPE
	,GL_SOUCHE + '-' + GL_CODEARTICLE AS YOUR_REFERENCE
	,GL_LIBREART6 AS MATERIAL_TYPE
	,(
		SELECT CASE WHEN YTC_TIERS <> '' THEN 'X' ELSE '' END
		FROM TIERSCOMPL
		WHERE YTC_TABLELIBRETIERS1 = '001' AND YTC_TIERS = A.GP_TIERS
		) AS EMPLOYEE_DISCOUNT
	,IIF(GL_LIBREART6 = 'Z002', '0', (
		CASE
			WHEN ISNULL(GL_PUHTBASE, 0) <> 0 AND (GL_PUTTC * GL_QTEFACT) - GL_TOTALTTC < 0
				THEN ABS(ROUND(((ISNULL(GL_PUTTC, 0) / 1.10) * GL_QTEFACT), 0) - GL_TOTALHT)
			WHEN ISNULL(GL_PUHTBASE, 0) <> 0 AND (GL_PUTTC * GL_QTEFACT) - GL_TOTALTTC > 0
				THEN ROUND(((ISNULL(GL_PUTTC, 0) / 1.10) * GL_QTEFACT), 0) - GL_TOTALHT
			WHEN ISNULL(GL_PUHTBASE, 0) = 0 AND (ISNULL(GF_PRIXUNITAIRE, 0)) = 0
				THEN GL_PUHT * GL_QTEFACT - GL_TOTALHT
			WHEN ISNULL(GL_PUHTBASE, 0) = 0 AND (ROUND(ISNULL(GF_PRIXUNITAIRE, 0) / 1.10, 0) * GL_QTEFACT) - GL_TOTALTTC < 0
				THEN ABS(ROUND(((ISNULL(GF_PRIXUNITAIRE, 0) / 1.10) * GL_QTEFACT), 0) - GL_TOTALHT)
			WHEN ISNULL(GL_PUHTBASE, 0) = 0 AND (ROUND(ISNULL(GF_PRIXUNITAIRE, 0) / 1.10, 0) * GL_QTEFACT) - GL_TOTALTTC > 0
				THEN ROUND(((ISNULL(GF_PRIXUNITAIRE, 0) / 1.10) * GL_QTEFACT), 0) - GL_TOTALHT
			ELSE 0
		END
	) * (1 - ET_VALLIBRE1 / 100)) AS HEADER_DISCOUNT_VALUE
	,A.GP_NATUREPIECEG
	,A.GP_SOUCHE
	,A.GP_NUMERO
	,A.GP_INDICEG
	,A.GP_ETATEXPORT
	,CASE
		WHEN A.GP_ETATEXPORT = 'ATT' THEN 'AT1'
		WHEN A.GP_ETATEXPORT = 'AT1' THEN 'AT2'
		WHEN A.GP_ETATEXPORT = 'AT2' THEN 'AT3'
		ELSE 'AT4'
	END AS EXPSTATUS
FROM PIECE A
JOIN LIGNE ON A.GP_NATUREPIECEG = GL_NATUREPIECEG
	AND A.GP_SOUCHE = GL_SOUCHE
	AND A.GP_NUMERO = GL_NUMERO
JOIN ETABLISS ON A.GP_ETABLISSEMENT = ET_ETABLISSEMENT
LEFT JOIN COMMERCIAL ON A.GP_REPRESENTANT = GCL_COMMERCIAL
/* =============================================
   COMPANY STORE: TIERS join is optional for company stores
   ============================================= */
LEFT JOIN ARTICLEDIM_MODE ON GA_ARTICLE = GL_ARTICLE
LEFT JOIN GCTARFCONMODEART ON GCTARFCONMODEART.GA_CODEARTICLE = GL_CODEARTICLE
	AND GF_REGIMEPRIX = 'TTC'
	AND (GCTARFCONMODEART.GA_STATUTART = 'GEN' OR GCTARFCONMODEART.GA_STATUTART = 'UNI')
	AND (GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('CSRSP'))
	AND GF_ARTICLE <> ''
	AND GF_DEVISE = 'KRW'
	AND GFM_TYPETARIF = 'CSRSP'
	AND GFM_PERTARIF = (
		SELECT TOP 1 TARIFMODE.GFM_PERTARIF
		FROM TARIF
		JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE
		WHERE TARIFMODE.GFM_DATEFIN > A.GP_DATEPIECE
			AND TARIFMODE.GFM_DATEDEBUT <= A.GP_DATEPIECE
			AND TARIF.GF_FERME = '-'
			AND TARIF.GF_ARTICLE = GL_CODEARTICLE + REPLICATE(' ', 33 - LEN(GL_CODEARTICLE)) + 'X'
		ORDER BY TARIFMODE.GFM_DATEDEBUT DESC
	)
	AND GFM_NATURETYPE = 'VTE'
	AND (GF_DEPOT = '' OR GF_DEPOT IS NULL)
	AND GF_PRIXUNITAIRE = (
		SELECT TOP 1 GF_PRIXUNITAIRE
		FROM GCTARFCONMODEART G2
		WHERE G2.GA_CODEARTICLE = GL_CODEARTICLE
			AND G2.GF_REGIMEPRIX = 'TTC'
			AND G2.GA_STATUTART IN ('GEN', 'UNI')
			AND G2.GF_ARTICLE <> ''
			AND G2.GF_DEVISE = 'KRW'
			AND G2.GFM_TYPETARIF = 'CSRSP'
			AND G2.GFM_NATURETYPE = 'VTE'
			AND (G2.GF_DEPOT = '' OR G2.GF_DEPOT IS NULL)
		ORDER BY G2.GF_PRIXUNITAIRE DESC
	)
/* =============================================
   COMPANY STORE: Join BP codes from User Fields 1-6
   ============================================= */
LEFT JOIN MCHPSUTILISATDATA SHIBP ON SHIBP.MUD_ENTITEMCD = 'ETA'
	AND SHIBP.MUD_CLEENTITE = GP_ETABLISSEMENT
	AND SHIBP.MUD_IDCHAMP = 1
LEFT JOIN MCHPSUTILISATDATA CPBBP ON CPBBP.MUD_ENTITEMCD = 'ETA'
	AND CPBBP.MUD_CLEENTITE = GP_ETABLISSEMENT
	AND CPBBP.MUD_IDCHAMP = 2
LEFT JOIN MCHPSUTILISATDATA NARBP ON NARBP.MUD_ENTITEMCD = 'ETA'
	AND NARBP.MUD_CLEENTITE = GP_ETABLISSEMENT
	AND NARBP.MUD_IDCHAMP = 3
LEFT JOIN MCHPSUTILISATDATA DREBP ON DREBP.MUD_ENTITEMCD = 'ETA'
	AND DREBP.MUD_CLEENTITE = GP_ETABLISSEMENT
	AND DREBP.MUD_IDCHAMP = 4
LEFT JOIN MCHPSUTILISATDATA FRABP ON FRABP.MUD_ENTITEMCD = 'ETA'
	AND FRABP.MUD_CLEENTITE = GP_ETABLISSEMENT
	AND FRABP.MUD_IDCHAMP = 5
LEFT JOIN MCHPSUTILISATDATA CPCBP ON CPCBP.MUD_ENTITEMCD = 'ETA'
	AND CPCBP.MUD_CLEENTITE = GP_ETABLISSEMENT
	AND CPCBP.MUD_IDCHAMP = 6
/* =============================================
   CONTRACTTYPE: Domain-aware BP code from ETA user fields
   Scalar subquery avoids CASE in JOIN ON (Cegid compatibility)
   ============================================= */
LEFT JOIN MCHPSUTILISATDATA CONTRACTTYPE ON CONTRACTTYPE.MUD_ENTITEMCD = 'CLI'
	AND CONTRACTTYPE.MUD_CLEENTITE = (
		SELECT CASE ARTICLEDIM_MODE.GA_DOMAINE
			WHEN 'SHI' THEN SHIBP.MUD_VALCHAMP
			WHEN 'CPB' THEN CPBBP.MUD_VALCHAMP
			WHEN 'NAR' THEN NARBP.MUD_VALCHAMP
			WHEN 'DRE' THEN DREBP.MUD_VALCHAMP
			WHEN 'FRA' THEN FRABP.MUD_VALCHAMP
			WHEN 'CPC' THEN CPCBP.MUD_VALCHAMP
			ELSE ''
		END
		FROM ARTICLEDIM_MODE
		JOIN MCHPSUTILISATDATA SHIBP ON SHIBP.MUD_ENTITEMCD = 'ETA' AND SHIBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND SHIBP.MUD_IDCHAMP = 1
		JOIN MCHPSUTILISATDATA CPBBP ON CPBBP.MUD_ENTITEMCD = 'ETA' AND CPBBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND CPBBP.MUD_IDCHAMP = 2
		JOIN MCHPSUTILISATDATA NARBP ON NARBP.MUD_ENTITEMCD = 'ETA' AND NARBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND NARBP.MUD_IDCHAMP = 3
		JOIN MCHPSUTILISATDATA DREBP ON DREBP.MUD_ENTITEMCD = 'ETA' AND DREBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND DREBP.MUD_IDCHAMP = 4
		JOIN MCHPSUTILISATDATA FRABP ON FRABP.MUD_ENTITEMCD = 'ETA' AND FRABP.MUD_CLEENTITE = ET_ETABLISSEMENT AND FRABP.MUD_IDCHAMP = 5
		JOIN MCHPSUTILISATDATA CPCBP ON CPCBP.MUD_ENTITEMCD = 'ETA' AND CPCBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND CPCBP.MUD_IDCHAMP = 6
		WHERE ARTICLEDIM_MODE.GA_ARTICLE = LIGNE.GL_ARTICLE
	)
	AND CONTRACTTYPE.MUD_IDCHAMP = 26
WHERE (
	/* =============================================
	   COMPANY STORE: Filter ET_LIBREET1 = '006'
	   ============================================= */
	/* FOR NORMAL FFO */
	(
		A.GP_NATUREPIECEG = 'FFO'
		AND GL_LIBREART6 <> 'Z002'
		AND GL_PUTTCBASE * GL_QTEFACT = GL_TOTALTTC
		AND GP_DATEPIECE >= '2026-04-01'
		AND ET_LIBREET1 = '006'
		AND NOT EXISTS (
			SELECT 1 FROM LIGNE LC
			WHERE LC.GL_NATUREPIECEG = A.GP_NATUREPIECEG
				AND LC.GL_SOUCHE = A.GP_SOUCHE
				AND LC.GL_NUMERO = A.GP_NUMERO
				AND LC.GL_PUTTCBASE <> 0
				AND LC.GL_QTEFACT > 0
				AND LC.GL_PUTTCBASE * LC.GL_QTEFACT <> LC.GL_TOTALTTC
				AND LC.GL_LIBREART6 <> 'Z002'
		)
	)
	/* FOR REPURCHASING */
	OR (
		A.GP_NATUREPIECEG = 'FFO'
		AND GL_LIBREART6 <> 'Z002'
		AND GP_DATEPIECE >= '20260401'
		AND ET_LIBREET1 = '006'
	)
)
	AND A.GP_TICKETANNULE = '-'
	AND ARTICLEDIM_MODE.GA_LIBREART6 IN ('Z001')
	AND GL_DATEPIECE >= '2026-04-01'
	AND GL_TYPEARTICLE <> ''
	AND GL_QTEFACT <> 0
	AND GP_SUPPRIME <> 'X'
	AND (
		CASE
			WHEN (
				SELECT CAST(GDI_LIBELLE AS VARCHAR)
				FROM DIMENSION
				INNER JOIN ARTICLE ON GDI_GRILLEDIM = GA_GRILLEDIM1
					AND GDI_CODEDIM = GA_CODEDIM1
				WHERE GDI_TYPEDIM = 'DI1'
					AND GA_ARTICLE = LIGNE.GL_ARTICLE
			) <> ''
				THEN (
					SELECT GA_CHARLIBRE1 + '-' + CAST(GDI_LIBELLE AS VARCHAR)
					FROM DIMENSION
					INNER JOIN ARTICLE ON GDI_GRILLEDIM = GA_GRILLEDIM1
						AND GDI_CODEDIM = GA_CODEDIM1
					WHERE GDI_TYPEDIM = 'DI1'
						AND GA_ARTICLE = LIGNE.GL_ARTICLE
				)
			ELSE CASE
					WHEN GA_CHARLIBRE1 <> '' THEN GA_CHARLIBRE1
					ELSE GL_CODEARTICLE
				END
		END
	) NOT IN ('')
ORDER BY A.GP_NATUREPIECEG
	,A.GP_SOUCHE
	,A.GP_NUMERO
	,A.GP_ETATEXPORT
	,GL_CODEARTICLE
