SELECT A.GP_NATUREPIECEG AS CEGID_DOCS_TYPE
	,'KR' AS SAP_COUNTRY_CODE
	,'8591' AS SALES_ORG
	,ET_LIBREET9 AS DIST_CHANNEL
	,ET_CHARLIBRE1 AS SOLD_TO
	/* =============================================
	   COMPANY STORE: SHIP_TO mapped by GA_domaine -> BP codes in User Fields 1-6
	   SHI -> UserField1, CPB -> UserField2, NAR -> UserField3, DRE -> UserField4, FRA -> UserField5, CPC -> UserField6
	   ============================================= */
	,CASE
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'SHI' THEN SHIBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'CPB' THEN CPBBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'NAR' THEN NARBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'DRE' THEN DREBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'FRA' THEN FRABP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'CPC' THEN CPCBP.MUD_VALCHAMP
		ELSE ET_CHARLIBRE2
	END AS SHIP_TO
	,A.GP_REPRESENTANT + ' ' + GCL_LIBELLE AS SENDER_BC
	,'' AS RECEIPIENT_BC
	,CASE
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1' THEN 'Z4OR'
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP IN ('K2', 'K3') THEN 'Z4KB'
		WHEN A.GP_NATUREPIECEG = 'CF' AND ET_LIBREET1 = '006' THEN 'Z4KB'
		ELSE ''
	END AS SALES_ORDER_TYPE
	,'Z517' AS PO_TYPE
	,CASE
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1'
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4OR'
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP IN ('K2', 'K3')
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4KB'
		WHEN A.GP_NATUREPIECEG = 'CF' AND ET_LIBREET1 = '006'
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4KB'
		ELSE ''
	END AS CUSTREF
	,CONVERT(NVARCHAR(8), A.GP_DATEPIECE, 112) AS PO_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATELIVRAISON, 112) AS REQUEST_DELIVERY_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATELIVRAISON, 112) AS CONTRACT_START_DATE
	,CONVERT(NVARCHAR(8), CONVERT(DATE, A.GP_DATELIVRAISON, 112) + 1, 112) AS CONTRACT_END_DATE
	,(
		SELECT YX_LIBELLE FROM CHOIXEXT
		WHERE YX_TYPE = 'GTL' AND YX_CODE LIKE 'Z01%'
		AND YX_ABREGE = ET_LIBREET9 + '-' + GL_MOTIFMVT
	) AS COST_CENTER
	,RIGHT('000000' + STR(GL_NUMORDRE), 6) AS ITEM_LINE_NUMBER
	,CASE WHEN GL_QTEFACT > 0 THEN GL_QTEFACT ELSE ABS(GL_QTEFACT) END AS ORDER_QUANTITY
	,ARTICLEDIM_MODE.GDI_LIBELLE_1 AS MATERIAL_NUMBER
	,'ZMP2' AS CONDITION_TYPE
	,IIF(GL_LIBREART6 = 'Z002' OR GL_QTEFACT = 0, '0', (
		CASE WHEN GL_NATUREPIECEG <> 'FFO' THEN ISNULL(GF_PRIXUNITAIRE, 0)
		WHEN ISNULL(GL_TOTALTTC, 0) > 0 THEN GL_TOTALTTC / GL_QTEFACT
		ELSE CASE WHEN GL_TOTALTTC = 0 THEN 0
		ELSE CASE WHEN ISNULL(GL_PUTTCBASE, 0) = 0 AND ISNULL(GF_PRIXUNITAIRE, 0) <> 0
			THEN ABS(ROUND(ISNULL(GF_PRIXUNITAIRE, 0), 2))
		ELSE ABS(ROUND(ISNULL(GL_PUTTC, 0), 2)) END END END
	)) AS RETAIL_PRICE
	,'' AS DISC_CONDITION_TYPE
	,'' AS DISCOUNT_AMT
	,CASE
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1' AND GL_LIBREART6 <> 'Z002' THEN 'TAN'
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1' AND GL_LIBREART6 = 'Z002' THEN 'TANN'
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP = 'K2' THEN 'KBN'
		WHEN A.GP_NATUREPIECEG = 'CF' AND CONTRACTTYPE.MUD_VALCHAMP = 'K3' THEN 'ZKBN'
		WHEN A.GP_NATUREPIECEG = 'CF' AND ET_LIBREET1 = '006' AND GL_LIBREART6 <> 'Z002' THEN 'KBN'
		WHEN A.GP_NATUREPIECEG = 'CF' AND ET_LIBREET1 = '006' AND GL_LIBREART6 = 'Z002' THEN 'KBN'
		ELSE ''
	END AS ITEM_CAT
	,'' AS SURCHARGE
	,'' AS ORDER_REASON
	,'8591' AS PLANT
	,'W001' AS SLOC
	,ARTICLEDIM_MODE.GDI_LIBELLE AS BATCH
	,CAST(ET_CHARLIBRE3 AS VARCHAR) + CONVERT(VARCHAR(8), NOW(), 112) + REPLACE(CONVERT(VARCHAR(5), ADDHOURS(NOW(), -7), 108), ':', '') AS MESSAGE_ID
	,CONVERT(VARCHAR(8), A.GP_DATEPIECE, 112) AS DATE
	,REPLACE(CONVERT(VARCHAR(5), ADDHOURS(NOW(), -7), 108), ':', '') AS TIME
	,CASE WHEN GL_QTEFACT < 0 THEN 'Z4KR' WHEN GL_LIBREART6 = 'Z002' THEN 'Z4FC' ELSE 'Z4KE' END AS ORDER_TYPE
	,GL_SOUCHE + '-' + GL_CODEARTICLE AS YOUR_REFERENCE
	,GL_LIBREART6 AS MATERIAL_TYPE
	,(
		SELECT CASE WHEN YTC_TIERS <> '' THEN 'X' ELSE '' END
		FROM TIERSCOMPL WHERE YTC_TABLELIBRETIERS1 = '001' AND YTC_TIERS = A.GP_TIERS
	) AS EMPLOYEE_DISCOUNT
	,'0' AS HEADER_DISCOUNT_VALUE
	,A.GP_NATUREPIECEG, A.GP_SOUCHE, A.GP_NUMERO, A.GP_INDICEG, A.GP_ETATEXPORT
	,CASE WHEN A.GP_ETATEXPORT = 'ATT' THEN 'AT1' ELSE 'AT1' END AS EXPSTATUS
	,CASE WHEN GP_UTILISATEUR<>'ADM' THEN 'ADM' ELSE 'ADM' END AS MODIFUSER
FROM PIECE A
JOIN LIGNE ON A.GP_NATUREPIECEG = GL_NATUREPIECEG AND A.GP_SOUCHE = GL_SOUCHE AND A.GP_NUMERO = GL_NUMERO
JOIN ETABLISS ON A.GP_ETABLISSEMENT = ET_ETABLISSEMENT
LEFT JOIN COMMERCIAL ON A.GP_REPRESENTANT = GCL_COMMERCIAL
LEFT JOIN TIERS ON ET_CHARLIBRE2 = T_TIERS
JOIN TIERSCOMPL ON T_TIERS = YTC_TIERS
LEFT JOIN ARTICLEDIM_MODE ON GA_ARTICLE = GL_ARTICLE
LEFT JOIN GCTARFCONMODEART ON GCTARFCONMODEART.GA_CODEARTICLE = GL_CODEARTICLE
	AND GF_REGIMEPRIX = 'TTC'
	AND (GCTARFCONMODEART.GA_STATUTART = 'GEN' OR GCTARFCONMODEART.GA_STATUTART = 'UNI')
	AND (GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('CSRSP'))
	AND GF_ARTICLE <> '' AND GF_DEVISE = 'KRW'
	AND GFM_TYPETARIF = 'CSRSP'
	AND GFM_PERTARIF = (
		SELECT TOP 1 TARIFMODE.GFM_PERTARIF FROM TARIF
		JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE
		WHERE TARIFMODE.GFM_DATEFIN > A.GP_DATEPIECE AND TARIFMODE.GFM_DATEDEBUT <= A.GP_DATEPIECE
		AND TARIF.GF_FERME = '-' AND TARIF.GF_ARTICLE = GL_CODEARTICLE + REPLICATE(' ', 33 - LEN(GL_CODEARTICLE)) + 'X'
		ORDER BY TARIFMODE.GFM_DATEDEBUT DESC)
	AND GFM_NATURETYPE = 'VTE' AND (GF_DEPOT = '' OR GF_DEPOT IS NULL)
LEFT JOIN MCHPSUTILISATDATA SHIBP ON SHIBP.MUD_ENTITEMCD = 'ETA' AND SHIBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND SHIBP.MUD_IDCHAMP = 1
LEFT JOIN MCHPSUTILISATDATA CPBBP ON CPBBP.MUD_ENTITEMCD = 'ETA' AND CPBBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND CPBBP.MUD_IDCHAMP = 2
LEFT JOIN MCHPSUTILISATDATA NARBP ON NARBP.MUD_ENTITEMCD = 'ETA' AND NARBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND NARBP.MUD_IDCHAMP = 3
LEFT JOIN MCHPSUTILISATDATA DREBP ON DREBP.MUD_ENTITEMCD = 'ETA' AND DREBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND DREBP.MUD_IDCHAMP = 4
LEFT JOIN MCHPSUTILISATDATA FRABP ON FRABP.MUD_ENTITEMCD = 'ETA' AND FRABP.MUD_CLEENTITE = ET_ETABLISSEMENT AND FRABP.MUD_IDCHAMP = 5
LEFT JOIN MCHPSUTILISATDATA CPCBP ON CPCBP.MUD_ENTITEMCD = 'ETA' AND CPCBP.MUD_CLEENTITE = ET_ETABLISSEMENT AND CPCBP.MUD_IDCHAMP = 6
LEFT JOIN MCHPSUTILISATDATA CARRYSALES ON CARRYSALES.MUD_ENTITEMCD = 'DOC'
	AND CARRYSALES.MUD_CLEENTITE = 'CF' + ';' + A.GP_SOUCHE + ';' + STR(A.GP_NUMERO) + ';' + STR(A.GP_INDICEG)
	AND CARRYSALES.MUD_IDCHAMP = 1 AND LEFT(CARRYSALES.MUD_VALCHAMP, 8) <> '19000101'
	AND LEFT(CARRYSALES.MUD_VALCHAMP, 8) <> CONVERT(CHAR(8), A.GP_DATEPIECE, 112)
LEFT JOIN MCHPSUTILISATDATA CONTRACTTYPE ON CONTRACTTYPE.MUD_ENTITEMCD = 'CLI'
	AND CONTRACTTYPE.MUD_CLEENTITE = T_TIERS AND CONTRACTTYPE.MUD_IDCHAMP = 35
WHERE A.GP_NATUREPIECEG IN ('CF')
	AND (A.GP_ETATEXPORT = 'ATT' OR (GP_DTSVLASTCHANGE>[#LAST_EXEC] AND A.GP_ETATEXPORT = 'AT1' AND GP_LIBREPIECE1<>'Z04YES' AND GP_UTILISATEUR<>'ADM'))
	AND GP_REPRESENTANT <> 'ONLINE' AND A.GP_TICKETANNULE = '-'
	AND ARTICLEDIM_MODE.GA_LIBREART6 IN ('Z001')
	AND GL_DATEPIECE >= '2026-04-01'
	AND GL_TYPEARTICLE <> '' AND GP_SUPPRIME<>'X' AND GL_QTEFACT <> 0
	AND ET_LIBREET1 = '006'
	AND (
		CASE WHEN (
			SELECT CAST(GDI_LIBELLE AS VARCHAR) FROM DIMENSION
			INNER JOIN ARTICLE ON GDI_GRILLEDIM = GA_GRILLEDIM1 AND GDI_CODEDIM = GA_CODEDIM1
			WHERE GDI_TYPEDIM = 'DI1' AND GA_ARTICLE = LIGNE.GL_ARTICLE
		) <> '' THEN (
			SELECT GA_CHARLIBRE1 + '-' + CAST(GDI_LIBELLE AS VARCHAR) FROM DIMENSION
			INNER JOIN ARTICLE ON GDI_GRILLEDIM = GA_GRILLEDIM1 AND GDI_CODEDIM = GA_CODEDIM1
			WHERE GDI_TYPEDIM = 'DI1' AND GA_ARTICLE = LIGNE.GL_ARTICLE
		) ELSE CASE WHEN GA_CHARLIBRE1 <> '' THEN GA_CHARLIBRE1 ELSE GL_CODEARTICLE END END
	) NOT IN ('')
ORDER BY A.GP_NATUREPIECEG, A.GP_SOUCHE, A.GP_NUMERO, A.GP_ETATEXPORT, GL_CODEARTICLE