SELECT A.GP_NATUREPIECEG AS CEGID_DOCS_TYPE
	,'KR' AS SAP_COUNTRY_CODE
	,'8591' AS SALES_ORG
	,ET_LIBREET9 AS DIST_CHANNEL
	,ET_CHARLIBRE1 AS SOLD_TO
	/* =============================================
	   COMPANY STORE: SHIP_TO mapped by GA_domaine -> BP codes in User Fields 1-6
	   ============================================= */
	,CASE
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'SHI' THEN SHIBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'CPB' THEN CPBBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'NAR' THEN NARBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'DRE' THEN DREBP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'FRA' THEN FRABP.MUD_VALCHAMP
		WHEN ARTICLEDIM_MODE.GA_DOMAINE = 'CPC' THEN CPCBP.MUD_VALCHAMP
		ELSE ET_CHARLIBRE2
	END AS SHIP_TO
	,A.GP_REPRESENTANT + ' ' + GCL_LIBELLE AS SENDER_BC
	,'' AS RECEIPIENT_BC
	,CASE
		/* K1 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1'
			THEN 'Z4RE'
		/* K2, K3 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP IN ('K2', 'K3')
			THEN 'Z4KA'
		/* COMPANY STORE: Hardcoded K2 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND ET_LIBREET1 = '006'
			THEN 'Z4KA'
		ELSE ''
	END AS SALES_ORDER_TYPE
	,'Z517' AS PO_TYPE
	,CASE
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1'
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4RE'
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP IN ('K2', 'K3')
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4KA'
		/* COMPANY STORE: Hardcoded K2 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND ET_LIBREET1 = '006'
			THEN TRIM(A.GP_NATUREPIECEG) + A.GP_SOUCHE + STR(A.GP_NUMERO) + STR(A.GP_INDICEG) + '_Z4KA'
		ELSE ''
	END AS CUSTREF
	,CONVERT(NVARCHAR(8), A.GP_DATEPIECE, 112) AS PO_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATELIVRAISON, 112) AS REQUEST_DELIVERY_DATE
	,CONVERT(NVARCHAR(8), A.GP_DATELIVRAISON, 112) AS CONTRACT_START_DATE
	,CONVERT(NVARCHAR(8), CONVERT(DATE, A.GP_DATELIVRAISON, 112) + 1, 112) AS CONTRACT_END_DATE
	,'' AS COST_CENTER
	,RIGHT('000000' + STR(GL_NUMORDRE), 6) AS ITEM_LINE_NUMBER
	,CASE
		WHEN GL_QTEFACT > 0
			THEN GL_QTEFACT
		ELSE ABS(GL_QTEFACT)
		END AS ORDER_QUANTITY
	,ARTICLEDIM_MODE.GDI_LIBELLE_1 AS MATERIAL_NUMBER
	,'ZMP2' AS CONDITION_TYPE
	,IIF(GL_LIBREART6 = 'Z002' OR GL_QTEFACT = 0, '0', (
		CASE
			WHEN GP_NATUREPIECEG = 'TEM' AND GP_DEPOTDEST LIKE '%T' AND GP_ETATEXPORT = 'AT1'
				THEN 0
			WHEN GL_NATUREPIECEG <> 'FFO'
				THEN ISNULL(GF_PRIXUNITAIRE, 0)
			WHEN ISNULL(GL_TOTALTTC, 0) > 0
				THEN GL_TOTALTTC / GL_QTEFACT
			ELSE CASE
					WHEN (GL_TOTALTTC = 0)
						THEN 0
					ELSE CASE
							WHEN ISNULL(GL_PUTTCBASE, 0) = 0
								AND ISNULL(GF_PRIXUNITAIRE, 0) <> 0
								THEN ABS(ROUND(ISNULL(GF_PRIXUNITAIRE, 0), 2))
							ELSE ABS(ROUND(ISNULL(GL_PUTTC, 0), 2))
							END
					END
			END
		)) AS RETAIL_PRICE
	,'' AS DISC_CONDITION_TYPE
	,'' AS DISCOUNT_AMT
	,CASE
		/* K1 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1' AND (GL_LIBREART6 = 'Z002' OR ISNULL(GF_PRIXUNITAIRE, 0) = 0)
			THEN 'RENN'
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1'
			THEN 'REN'
		/* K2 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K2'
			THEN 'KAN'
		/* K3 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K3'
			THEN 'ZKAN'
		/* COMPANY STORE: Hardcoded K2 */
		WHEN A.GP_NATUREPIECEG = 'BFA' AND ET_LIBREET1 = '006' AND (GL_LIBREART6 = 'Z002' OR ISNULL(GF_PRIXUNITAIRE, 0) = 0)
			THEN 'KAN'
		WHEN A.GP_NATUREPIECEG = 'BFA' AND ET_LIBREET1 = '006'
			THEN 'KAN'
		ELSE ''
	END AS ITEM_CAT
	,'' AS SURCHARGE
	,CASE
		/* K1 */
		WHEN GL_MOTIFMVT = '400' AND A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP = 'K1'
			THEN '402'
		/* K2, K3 */
		WHEN GL_MOTIFMVT = '400' AND A.GP_NATUREPIECEG = 'BFA' AND CONTRACTTYPE.MUD_VALCHAMP IN ('K2', 'K3')
			THEN '519'
		/* COMPANY STORE: Hardcoded K2 */
		WHEN GL_MOTIFMVT = '400' AND A.GP_NATUREPIECEG = 'BFA' AND ET_LIBREET1 = '006'
			THEN '519'
		ELSE TRIM(GL_MOTIFMVT)
	END AS ORDER_REASON
	,'8591' AS PLANT
	,'W010' AS SLOC
	,CASE
		WHEN A.GP_NATUREPIECEG = 'BFA' THEN ARTICLEDIM_MODE.GDI_LIBELLE
		ELSE 'CONSIGN'
	END AS BATCH
	,A.GP_NATUREPIECEG
	,A.GP_SOUCHE
	,A.GP_NUMERO
	,A.GP_INDICEG
	,A.GP_ETATEXPORT
	,CASE
		WHEN A.GP_ETATEXPORT = 'ATT' THEN 'AT1'
		WHEN A.GP_ETATEXPORT = 'AT1' THEN 'AT2'
		WHEN A.GP_ETATEXPORT = 'AT2' THEN 'AT3'
		ELSE 'AT4'
	END AS EXPSTATUS
FROM PIECE A
JOIN LIGNE ON A.GP_NATUREPIECEG = GL_NATUREPIECEG
	AND A.GP_SOUCHE = GL_SOUCHE
	AND A.GP_NUMERO = GL_NUMERO
JOIN ETABLISS ON A.GP_ETABLISSEMENT = ET_ETABLISSEMENT
LEFT JOIN COMMERCIAL ON A.GP_REPRESENTANT = GCL_COMMERCIAL
/* =============================================
   COMPANY STORE: TIERS join is optional for company stores
   ============================================= */
LEFT JOIN TIERS ON ET_CHARLIBRE2 = T_TIERS
JOIN TIERSCOMPL ON T_TIERS = YTC_TIERS
LEFT JOIN ARTICLEDIM_MODE ON GA_ARTICLE = GL_ARTICLE
/* =============================================
   COMPANY STORE: GFM_TYPETARIF = 'CSRSP' instead of 'KRRSP'
   ============================================= */
LEFT JOIN GCTARFCONMODEART ON GCTARFCONMODEART.GA_CODEARTICLE = GL_CODEARTICLE
	AND (
		GF_REGIMEPRIX = 'TTC'
		AND (
			(
				GCTARFCONMODEART.GA_STATUTART = 'GEN'
				OR GCTARFCONMODEART.GA_STATUTART = 'UNI'
				)
			AND (
				GFM_TYPETARIF IS NULL
				OR GFM_TYPETARIF IN ('CSRSP')  /* COMPANY STORE: Changed from 'KRRSP' to 'CSRSP' */
				)
			AND GF_ARTICLE <> ''
			)
		AND GF_DEVISE = 'KRW'
		AND GFM_TYPETARIF = 'CSRSP'  /* COMPANY STORE: Changed from 'KRRSP' to 'CSRSP' */
		AND GFM_PERTARIF = (
			SELECT TOP 1 TARIFMODE.GFM_PERTARIF
			FROM TARIF
			JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE
			WHERE TARIFMODE.GFM_DATEFIN > A.GP_DATEPIECE
				AND TARIFMODE.GFM_DATEDEBUT <= A.GP_DATEPIECE
				AND TARIF.GF_FERME = '-'
				AND TARIF.GF_ARTICLE = GL_CODEARTICLE + REPLICATE(' ', 33 - LEN(GL_CODEARTICLE)) + 'X'
			ORDER BY TARIFMODE.GFM_DATEDEBUT DESC
			)
		AND GFM_NATURETYPE = 'VTE'
		AND (
			(GF_DEPOT = '')
			OR (GF_DEPOT IS NULL)
			)
		)
/* =============================================
   COMPANY STORE: Join BP codes from User Fields 1-6
   ============================================= */
LEFT JOIN MCHPSUTILISATDATA SHIBP ON SHIBP.MUD_ENTITEMCD = 'ETA'
	AND SHIBP.MUD_CLEENTITE = ET_ETABLISSEMENT
	AND SHIBP.MUD_IDCHAMP = 1
LEFT JOIN MCHPSUTILISATDATA CPBBP ON CPBBP.MUD_ENTITEMCD = 'ETA'
	AND CPBBP.MUD_CLEENTITE = ET_ETABLISSEMENT
	AND CPBBP.MUD_IDCHAMP = 2
LEFT JOIN MCHPSUTILISATDATA NARBP ON NARBP.MUD_ENTITEMCD = 'ETA'
	AND NARBP.MUD_CLEENTITE = ET_ETABLISSEMENT
	AND NARBP.MUD_IDCHAMP = 3
LEFT JOIN MCHPSUTILISATDATA DREBP ON DREBP.MUD_ENTITEMCD = 'ETA'
	AND DREBP.MUD_CLEENTITE = ET_ETABLISSEMENT
	AND DREBP.MUD_IDCHAMP = 4
LEFT JOIN MCHPSUTILISATDATA FRABP ON FRABP.MUD_ENTITEMCD = 'ETA'
	AND FRABP.MUD_CLEENTITE = ET_ETABLISSEMENT
	AND FRABP.MUD_IDCHAMP = 5
LEFT JOIN MCHPSUTILISATDATA CPCBP ON CPCBP.MUD_ENTITEMCD = 'ETA'
	AND CPCBP.MUD_CLEENTITE = ET_ETABLISSEMENT
	AND CPCBP.MUD_IDCHAMP = 6
LEFT JOIN MCHPSUTILISATDATA CONTRACTTYPE ON CONTRACTTYPE.MUD_ENTITEMCD = 'CLI'
	AND CONTRACTTYPE.MUD_CLEENTITE = T_TIERS
	AND CONTRACTTYPE.MUD_IDCHAMP = 35
WHERE (
		(
			A.GP_NATUREPIECEG IN ('BFA')
			AND A.GP_ETATEXPORT = 'ATT'
			AND A.GP_REPRESENTANT <> 'ONLINE'
		)
	)
	AND A.GP_TICKETANNULE = '-'
	AND ARTICLEDIM_MODE.GA_LIBREART6 IN ('Z001')
	AND GL_DATEPIECE >= '20260401'
	AND GL_TYPEARTICLE <> ''
	AND GP_SUPPRIME <> 'X'
	AND GL_QTEFACT <> 0
	/* =============================================
	   COMPANY STORE: Filter stores with ET_LIBREET1 = '006'
	   ============================================= */
	AND ET_LIBREET1 = '006'
	AND (
		CASE
			WHEN (
					SELECT CAST(GDI_LIBELLE AS VARCHAR)
					FROM DIMENSION
					INNER JOIN ARTICLE ON GDI_GRILLEDIM = GA_GRILLEDIM1
						AND GDI_CODEDIM = GA_CODEDIM1
					WHERE GDI_TYPEDIM = 'DI1'
						AND GA_ARTICLE = LIGNE.GL_ARTICLE
					) <> ''
				THEN (
						SELECT GA_CHARLIBRE1 + '-' + CAST(GDI_LIBELLE AS VARCHAR)
						FROM DIMENSION
						INNER JOIN ARTICLE ON GDI_GRILLEDIM = GA_GRILLEDIM1
							AND GDI_CODEDIM = GA_CODEDIM1
						WHERE GDI_TYPEDIM = 'DI1'
							AND GA_ARTICLE = LIGNE.GL_ARTICLE
						)
			ELSE CASE
					WHEN GA_CHARLIBRE1 <> ''
						THEN GA_CHARLIBRE1
					ELSE GL_CODEARTICLE
					END
			END
		) NOT IN ('')
ORDER BY A.GP_NATUREPIECEG
	,A.GP_SOUCHE
	,A.GP_NUMERO
	,A.GP_ETATEXPORT
	,GL_CODEARTICLE